-- CRIA O BANCO LOJA CASO NÃO EXISTA
CREATE DATABASE IF NOT EXISTS loja_produtos;
-- SELECIONAR PARA USO
use loja_produtos;
-- CRIAR TABELA DE PRODUTOS
CREATE TABLE produtos (
	id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    preco DECIMAL(10, 2) NOT NULL
);